import SessionProviderWrapper from "@/app/components/SessionProviderWrapper"; // Adjust the import path as needed
import './globals.css';

export const metadata = {
  title: "Lingo AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>{children}</SessionProviderWrapper>
      </body>
    </html>
  );
}
